<a href="https://colab.research.google.com/github/TiagoIesbick/dashboard-etl/blob/main/monthly_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
def filter_window(df, date_col='DATE', months=12, extra_years=(1,2)):
    today = pd.Timestamp.today()
    cutoff = today.to_period('M').to_timestamp() - pd.DateOffset(months=1)
    start = cutoff - pd.DateOffset(months=months-1)

    mask_main = (df[date_col] >= start) & (df[date_col] <= cutoff)
    extra_dates = [cutoff - pd.DateOffset(years=y) for y in extra_years]

    return df[mask_main | df[date_col].isin(extra_dates)]

def group_cols(df, cols_to_delete=None):
    cols_to_delete = set(cols_to_delete or [])
    return [c for c in df.columns if c not in cols_to_delete]

In [3]:
df_exp = pd.read_csv(r'/content/drive/MyDrive/Dashboard_data/final_data/df_exp.csv', sep=';', parse_dates=['Comp.pagto.'])
df_rev = pd.read_csv(r'/content/drive/MyDrive/Dashboard_data/final_data/df_rev.csv', sep=";", parse_dates=['Data'])
df_exp = filter_window(df_exp, date_col='Comp.pagto.')
df_rev = filter_window(df_rev, date_col='Data')

In [4]:
df_rev.groupby(by=group_cols(df_rev, ['valor_arrecadado']), as_index=False).sum()

,Data,vinculo,origem,tipo,nome_rubrica,valor_arrecadado
0,2024-02-01,6049,Contribuições,Contr.Patronal - Servidor Civil Ativo - Dívida...,Contr.Patronal - Servid. Cedidos - Dívida Ativ...,4061.83
1,2024-02-01,6049,Contribuições,Contr.Patronal - Servidor Civil Ativo - Dívida...,Contr.Patr.- Cedidos - Dív. Ativa - Multas Jur...,4035.91
2,2024-02-01,6049,Contribuições,Contr.Patronal - Servidor Civil Ativo - Principal,Contr.Patronal - Servidores Cedidos - Plano em...,6012.69
3,2024-02-01,6049,Contribuições,Contr.do Servidor Civil - Pensionistas - Princ...,Contr.do Serv.Civil -Pensionistas - Plano em R...,692718.26
4,2024-02-01,6049,Contribuições,Contr.do Servidor Civil - Pensionistas - Princ...,Contr.do Servidor Civil - Pensionistas - Plano...,51676.82
...,...,...,...,...,...,...
1496,2026-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Re...,31293.30
1497,2026-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Re...,5091.19
1498,2026-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr.Patronal - Servidor Ativo - Plano em Cap...,1708044.37
1499,2026-02-01,6069,Outras Receitas Correntes,Outras Restituições - Principal,Restituições de Servidores FOPAG Exercício Cor...,941.79
1500,2026-02-01,6069,Receita Patrimonial Intra-Orçamentárias,Aluguéis e Arrendamentos - Principal,Aluguéis de Imóveis Públicos - RPPS - Intra Or...,20900.00

In [5]:
df_exp.groupby(by=group_cols(df_exp, ['Result. pago']), as_index=False).sum()

,Comp.pagto.,Unid. Orçam.,Proj/Ativ,Rubrica,Vinc. Orçam.,Elemento,Result. pago
0,2024-02-01,7001,2529,33901414,6069,339014,1836.34
1,2024-02-01,7001,2529,33903016,6069,339030,118.00
2,2024-02-01,7001,2529,33903022,6069,339030,2236.08
3,2024-02-01,7001,2529,33903702,6069,339037,11999.89
4,2024-02-01,7001,2529,33903703,6069,339037,12395.82
...,...,...,...,...,...,...,...
1680,2026-02-01,7003,2782,31900101,6050,319001,26222.38
1681,2026-02-01,7003,9075,33903903,6050,339039,10352.19
1682,2026-02-01,7003,9077,31908601,6050,319086,2275.86
1683,2026-02-01,7003,9077,31908603,6050,319086,84.95
1684,2026-02-01,7003,9077,31908604,6050,319086,107.13

In [6]:
df_rev

,Data,vinculo,origem,tipo,nome_rubrica,valor_arrecadado
11568,2024-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Ca...,11391.54
11569,2024-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Re...,40916.98
11570,2024-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Ca...,110119.28
11571,2024-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Re...,153363.35
11572,2024-02-01,6069,Contribuições Intra-Orçamentárias,Contr. Patronal - Servidor Civil Ativo - Princ...,Contr. Patronal - Servidor Ativo - Plano em Re...,63356.64
...,...,...,...,...,...,...
14294,2026-02-01,6050,Contribuições Intra-Orçamentárias,Contr.Patronal - Parcelamentos - Servidor Civi...,Parcel. Déb. - Patr. - Termo 00682/18 - LEI 12...,576605.68
14295,2026-02-01,6049,Contribuições Intra-Orçamentárias,Contr.Patronal - Servidor Civil Inativo - Prin...,Contr.Patr. - Serv. Civil Inativo - Plano em R...,5077.04
14296,2026-02-01,6050,Contribuições,Contr.do Servidor Civil - Pensionistas - Princ...,Contr.do Servidor Civil - Pensionistas - Plano...,811.44
14297,2026-02-01,6050,Contribuições,Contr.do Servidor Civil - Pensionistas - Princ...,Contr.do Servidor Civil - Pensionistas - Plano...,51151.18
14298,2026-02-01,6050,Contribuições Intra-Orçamentárias,Contr.Patronal - Parcelamentos - Servidor Civi...,Parcel. Déb. - Patr. - Termo 00682/18 - LEI 12...,334.74

In [7]:
df_exp

,Comp.pagto.,Result. pago,Unid. Orçam.,Proj/Ativ,Rubrica,Vinc. Orçam.,Elemento
50146,2024-02-01,6316.40,7001,2529,33903904,6069,339039
50147,2024-02-01,1836.34,7001,2529,33901414,6069,339014
50148,2024-02-01,118.00,7001,2529,33903016,6069,339030
50149,2024-02-01,2236.08,7001,2529,33903022,6069,339030
50150,2024-02-01,11999.89,7001,2529,33903702,6069,339037
...,...,...,...,...,...,...,...
53265,2026-02-01,225538.91,7003,2778,31900101,6050,319001
53266,2026-02-01,13974.44,7002,9076,31908602,6049,319086
53267,2026-02-01,11795.52,7003,2780,31900101,6050,319001
53268,2026-02-01,79682.68,7002,2751,31900301,6049,319003
53269,2026-02-01,82690.41,7003,2776,31900101,6050,319001

In [8]:
df_rev[['Data', 'valor_arrecadado']].groupby(by='Data').sum()

            valor_arrecadado
Data
2024-02-01      1.743052e+08
2025-02-01      2.251484e+08
2025-03-01      1.610294e+08
2025-04-01      1.688825e+08
2025-05-01      2.113979e+08
2025-06-01      1.621698e+08
2025-07-01      1.744459e+08
2025-08-01      2.294966e+08
2025-09-01      1.711755e+08
2025-10-01      1.726173e+08
2025-11-01      2.171452e+08
2025-12-01      2.310759e+08
2026-01-01      1.952684e+08
2026-02-01      1.695629e+08

In [25]:
sorted(df_rev['nome_rubrica'].unique())

['Alienação de Bens Imóveis - RPPS',
 'Aluguéis Diversos - Taxa de Administração - INTRA ORCAMENTÄRIA',
 'Aluguéis de Imóveis Públicos - RPPS - Intra Orçamentária',
 'Comp. Finan. RPPS/RPPS - Estados - Plano em Capitalização',
 'Comp. Finan. RPPS/RPPS - Estados - Plano em Repartição',
 'Comp. Finan. RPPS/RPPS - Municípios - Plano em Capitalização',
 'Comp. Finan. RPPS/RPPS - Municípios - Plano em Repartição',
 'Comp. Finan. RPPS/RPPS - União - Plano em Capitalização',
 'Comp. Financ. entre o Regime Geral e os RPPS - Plano em Capitalização',
 'Comp.Finan. Reg. Geral/RPPS - Plano em Capitalização-Multas e Juros',
 'Comp.Finan.RPPS/RPPS - Municípios - Plano em Repartição-Multas e Juros',
 'Comp.Finan.RPPS/RPPS-Estados-Plano em Repartição-Multas e Juros',
 'Comp.Finan.RPPS/RPPS-Municípios-Plano em Capitalização-Multas e Juros',
 'Compensações Financ entre o Regime Geral e os RPPS-Plano em Repartição',
 'Contr. Patr. Suplementar - Serv. Ativo - Plano em Capitalização - DMAE',
 'Contr. Patr. Suplementar - Serv. Ativo - Plano em Capitalização - DMLU',
 'Contr. Patr. Suplementar - Serv. Ativo - Plano em Capitalização - FASC',
 'Contr. Patronal - Servidor Ativo - Plano em Capitalização - CMPA',
 'Contr. Patronal - Servidor Ativo - Plano em Capitalização - DEMHAB',
 'Contr. Patronal - Servidor Ativo - Plano em Capitalização - DMAE',
 'Contr. Patronal - Servidor Ativo - Plano em Capitalização - DMLU',
 'Contr. Patronal - Servidor Ativo - Plano em Capitalização - FASC',
 'Contr. Patronal - Servidor Ativo - Plano em Capitalização - PREVIMPA',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - CMPA',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - Centralizada',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - DEMHAB',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - DMAE',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - DMLU',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - FASC',
 'Contr. Patronal - Servidor Ativo - Plano em Repartição - PREVIMPA',
 'Contr.Patr. - Serv. Civil Inativo - Plano em Repartição - Centralizada',
 'Contr.Patr. - Servidor Civil Inativo - Plano em Repartição - DEMHAB',
 'Contr.Patr. Supl.- Serv. Ativo - Plano em Capitalização - Centralizada',
 'Contr.Patr.- Cedidos - Dív. Ativa - Multas Juros - Plano em Repartição',
 'Contr.Patr.Suplementar - Serv. Ativo - Plano em Capitalização - DEMHAB',
 'Contr.Patronal - Afastados-Dív. Ativa-Multas Juros-Plano em Repartição',
 'Contr.Patronal - Serv. Afast.- Multas Juros-Plano em Capitaliz.-Normal',
 'Contr.Patronal - Serv. Afastados - Dívida Ativa - Plano em Repartição',
 'Contr.Patronal - Serv. Afastados - Plano em Capitaliz. - Alíq. Normal',
 'Contr.Patronal - Serv. Cedidos - Plano em Capitalização - Alíq. Normal',
 'Contr.Patronal - Servid. Cedidos - Dívida Ativa - Plano em Repartição',
 'Contr.Patronal - Servidor Ativo - Plano em Capitalização -Centralizada',
 'Contr.Patronal - Servidores Afastados - Plano em Repartição',
 'Contr.Patronal - Servidores Cedidos - Plano em Repartição',
 'Contr.Patronal Supl. - Serv. Ativo - Plano em Capitalização - PREVIMPA',
 'Contr.Serv.Ativo Afastado-Dív.Ativa-Multas Juros - Plano em Repartição',
 'Contr.Serv.Ativo Cedido-Dív.Ativa-Multas e Juros - Plano em Repartição',
 'Contr.Serv.Civil Ativo - Afastado - Dívida Ativa - Plano em Repartição',
 'Contr.Serv.Civil Ativo - Cedido - Dívida Ativa - Plano em Repartição',
 'Contr.Serv.Civil Ativo - Multas e Juros - Plano em Repartição - ORGÃOS DIVERSOS',
 'Contr.Serv.Civil Ativo- Afastado -Multas Juros -Plano em Capitalização',
 'Contr.Serv.Civil Ativo-Cedido-Multas e Juros - Plano em Capitalização',
 'Contr.do Serv. Civil - Pensionistas - Plano em Capitalização - DEMHAB',
 'Contr.do Serv. Civil-Pensionistas-Plano em Capitalização-Centralizada',
 'Contr.do Serv.Civil -Pensionistas - Plano em Repartição - Centralizada',
 'Contr.do Servidor Civil - Pensionistas - Plano em Capitalização - CMPA',
 'Contr.do Servidor Civil - Pensionistas - Plano em Capitalização - DMAE',
 'Contr.do Servidor Civil - Pensionistas - Plano em Capitalização - DMLU',
 'Contr.do Servidor Civil - Pensionistas - Plano em Capitalização - FASC',
 'Contr.do Servidor Civil - Pensionistas - Plano em Repartição - CMPA',
 'Contr.do Servidor Civil - Pensionistas - Plano em Repartição - DEMHAB',
 'Contr.do Servidor Civil - Pensionistas - Plano em Repartição - DMAE',
 'Contr.do Servidor Civil - Pensionistas - Plano em Repartição - DMLU',
 'Contr.do Servidor Civil - Pensionistas - Plano em Repartição - FASC',
 'Contr.do Servidor Civil -Pensionistas - Plano em Repartição - PREVIMPA',
 'Contr.do Servidor Civil Ativo -  Plano em Repartição - DMAE',
 'Contr.do Servidor Civil Ativo - Afastado - Plano em Capitalização',
 'Contr.do Servidor Civil Ativo - Afastado - Plano em Repartição',
 'Contr.do Servidor Civil Ativo - Cedido - Plano em Capitalização',
 'Contr.do Servidor Civil Ativo - Cedido - Plano em Repartição',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - CMPA',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - Centralizada',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - DEMHAB',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - DMAE',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - DMLU',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - FASC',
 'Contr.do Servidor Civil Ativo - Plano em Capitalização - PREVIMPA',
 'Contr.do Servidor Civil Ativo - Plano em Repartição - CMPA',
 'Contr.do Servidor Civil Ativo - Plano em Repartição - Centralizada',
 'Contr.do Servidor Civil Ativo - Plano em Repartição - DEMHAB',
 'Contr.do Servidor Civil Ativo - Plano em Repartição - DMLU',
 'Contr.do Servidor Civil Ativo - Plano em Repartição - FASC',
 'Contr.do Servidor Civil Ativo - Plano em Repartição - PREVIMPA',
 'Contr.do Servidor Civil Inativo - Plano em Capitalização - CMPA',
 'Contr.do Servidor Civil Inativo - Plano em Capitalização - DEMHAB',
 'Contr.do Servidor Civil Inativo - Plano em Capitalização - DMAE',
 'Contr.do Servidor Civil Inativo - Plano em Capitalização - DMLU',
 'Contr.do Servidor Civil Inativo - Plano em Capitalização - FASC',
 'Contr.do Servidor Civil Inativo - Plano em Capitalização - PREVIMPA',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - CMPA',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - Centralizada',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - DEMHAB',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - DMAE',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - DMLU',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - FASC',
 'Contr.do Servidor Civil Inativo - Plano em Repartição - PREVIMPA',
 'Contr.do Servidor Civil Inativo -Plano em Capitalização - Centralizada',
 'Dividendos - Plano em Capitalização',
 'Encargo Social - LC n.º 926/2021 - Plano em Repartição - Centralizada',
 'Encargo Social - LC n.º 926/2021 - Plano em Repartição - DEMHAB',
 'Encargo Social - LC n.º 926/2021 - Plano em Repartição - DMAE',
 'Encargo Social - LC n.º 926/2021 - Plano em Repartição - DMLU',
 'Encargo Social - LC n.º 926/2021 - Plano em Repartição - FASC',
 'Fundos de Investimentos em Renda Fixa',
 'Fundos de Investimentos em Renda Fixa Liquidez Imediata',
 'Fundos de Investimentos em Renda Variável',
 'Juros Semestrais',
 'Juros sobre Capital Próprio',
 'Juros sobre Capital Próprio - RPPS',
 'Outras Receitas - Descontos Obtidos - Taxa de Administração do RPPS',
 'Parc.de Débitos-Patronal-LC nº 637/2010-DEMHAB-Multas e Juros',
 'Parcel. Déb. - Patr. - Termo 00682/18 - LEI 12.371/2018 - Centralizada',
 'Parcel. Déb. - Patr. - Termo 00682/18 - LEI 12.371/2018 - DEMHAB',
 'Parcel. Déb. - Patr. - Termo 00682/18 - LEI 12.371/2018 - DMLU',
 'Parcel. Déb. - Patr. - Termo 00682/18 - LEI 12.371/2018 - FASC',
 'Parcel. Déb. Patr. - Termo 682/18 - LEI 12.371/2018-DEMHAB-Multa e Juros',
 'Parcel. Déb. Patr. - Termo 682/18 - LEI 12.371/2018-FASC-Multa e Juros',
 'Parcelamento de Débitos - Patronal - LC nº 637/2010 - Centralizada',
 'Parcelamento de Débitos - Patronal - LC nº 637/2010 - DEMHAB',
 'Parcelamento de Débitos - Patronal - LC nº 637/2010 - DMAE',
 'Parcelamento de Débitos - Patronal - LC nº 637/2010 - DMLU',
 'Prov. Pgto Benef. Prev. Indevido - Dívida Ativa - Plano em Repartição',
 'Prov.Pgto Benef.Prev. Indevido - Dívida Ativa - Fundo em Capitalização',
 'Restituição de Benefícios Previdenciários',
 'Restituição de Remuneração de FOPAG Exercícios Encerrados - Pessoal Ativo - Adm Indireta',
 'Restituições Diversas - RPPS - Plano em Repartição',
 'Restituições Diversas - Taxa de Administração do RPPS',
 'Restituições de Servidores - RPPS - Plano em Capitalização',
 'Restituições de Servidores - RPPS - Plano em Repartição',
 'Restituições de Servidores - Taxa de Administração do RPPS',
 'Restituições de Servidores FOPAG Exercício Corrente - Adm. Direta/Indireta/RPPS',
 'Sobra de Adiantamento de Numerário - Taxa de Administração do RPPS',
 'Taxa de Administração - INTRA ORCAMENTÄRIA']